### ISSUE TITLE
failDayProbs should take time into account

### ISSUE THREAD

**Issue by lluckydog** [MatthewLM/OptimumPeercoinUTXO#1]
I see the probabilities like ` failDayProbs = (1 - probSecs*adj)**SECDAY`, it seems not to take day into account when accumulate in the time

**Comment by MatthewLM** [comment]
Thanks for the issue. The `probSecs` comes from `dayWeights` which adjusts for the days between 30 and 60 by default. Does that explain it?

**Comment by lluckydog** [comment]
I wonder when the day time grows, like 100 days, is this `probSecs ` still sound good to simulate the possibility

**Comment by MatthewLM** [comment]
It rises linearly according to the day up-to the maximum probability which is reached after `RAMP_UP` days:

```python
# Max weight is the ramp up or assume a constant half day if no ramp up
maxDayWeight = RAMP_UP if RAMP_UP > 0 else RAMP_UP+0.5
# Offset by 0.5 to assume middle of day
dayWeights = np.clip(np.arange(MAX_DAYS) + 0.5, 0, maxDayWeight)
```

**Comment by MatthewLM** [comment]
Weird that I did `RAMP_UP if RAMP_UP > 0 else RAMP_UP+0.5` and not `RAMP_UP if RAMP_UP > 0 else 0.5`. No need for `RAMP_UP` at the end when it is zero.

**Comment by lluckydog** [comment]
thank you for your kind explanation
